### ISSUE TITLE
Dependency of `laminas/laminas-servicemanager` can be removed

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-crypt#27]
### Feature Request

|    Q        |   A
|------------ | ------
| BC Break    | no

#### Summary

Hey there, I realized that this component still depends on servicemanager while it provides its own `ContainerInterface` implementation.

**Comment by Ocramius** [comment]
This one? 


https://github.com/laminas/laminas-crypt/blob/56ab1b195dad5456753601ff2e8e3d3fd9392d1a/src/Symmetric/PaddingPluginManager.php#L17

Yep, we can drop the dependency :+1: 

Note that upgrading to `psr/container:^2` is trickier, because the implementations are not `final`

**Comment by gsteel** [comment]
Closed via #33
