### ISSUE TITLE
`PHP 8.2 Deprecated:  Creation of dynamic property Laminas\Crypt\Symmetric\Openssl::$supportedAlgos` error

### ISSUE THREAD

**Issue by basselin** [laminas/laminas-crypt#29]
### Bug Report

The property `$supportedAlgos` is not declared in `Laminas\Crypt\Symmetric\Openssl`

|    Q        |   A
|------------ | ------
| Version(s)  | 3.9.0

#### Summary

Error message : 
`PHP Deprecated:  Creation of dynamic property Laminas\Crypt\Symmetric\Openssl::$supportedAlgos is deprecated in /vendor/laminas/laminas-crypt/src/Symmetric/Openssl.php on line 663`

#### Current behavior

Deprecated message.

#### Expected behavior

Nothing more, just add : 
`protected $supportedAlgos;`

**Comment by Ocramius** [comment]
Send a patch to the current stable branch 👍.

I would suggest:

 * Marking the property `public`
 * Marking it `@internal` and documenting that it's only there for BC purposes
