### ISSUE TITLE
remove deprecated $supportedMhashAlgos values for Zend\Crypt\Key\Derivation\SaltedS2k

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-crypt#3]
---

Originally posted by @samsonasik at https://github.com/zendframework/zend-crypt/pull/46

**Comment by weierophinney** [comment]
I've labeled this as a BC break. We cannot remove these until our minimum PHP version is 7.2 or higher (as that is the first version where they will no longer be in core.

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-crypt/pull/46#issuecomment-384067734

**Comment by samsonasik** [comment]
I created PR #8 for it.

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
