### ISSUE TITLE
Consider libsodium / sodium_compat for modern public-key crypto

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-crypt#4]
https://github.com/paragonie/sodium_compat#cryptography-primitives-provided

Zend\Crypt users interested in modern ECC may want to see sodium_compat adopted in the near future. In particular, public-key encryption via `ParagonIE_Sodium_Compat::crypto_box_seal()` and digital signatures via `ParagonIE_Sodium_Compat::crypto_sign_detached()`.

I would, however, wait until sodium_compat has been audited first: https://github.com/paragonie/sodium_compat/issues/8

---

Originally posted by @paragonie-scott at https://github.com/zendframework/zend-crypt/issues/43

**Comment by weierophinney** [comment]
[v1.0.1](https://github.com/paragonie/sodium_compat/releases/tag/v1.0.1) is out, the notes from [v1.0.0](https://github.com/paragonie/sodium_compat/releases/tag/v1.0.0) are a must read before weighing whether or not to use it.

---

Originally posted by @paragonie-scott at https://github.com/zendframework/zend-crypt/issues/43#issuecomment-307533002

**Comment by paragonie-security** [comment]
We'd like to add that a lot of changes (including better support for 32-bit platforms) have landed since v1.0.0. The latest version is v1.12.2, which has been adopted by WordPress without major issue.

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
