### ISSUE TITLE
old module is not marked as abandoned

### ISSUE THREAD

**Issue by kokspflanze** [laminas/laminas-crypt#5]
The old Module https://packagist.org/packages/zendframework/zend-crypt is not marked as abandoned

btw same for 
https://packagist.org/packages/zendframework/zend-text
https://packagist.org/packages/zendframework/zend-mvc-plugin-prg
and some more but i dont want to create an issue for each module, maybe you can recheck it

@weierophinney

**Comment by weierophinney** [comment]
We mentioned this specifically in the announcement blog post:

> We still have a few things to iron out:
> 
 > - The Packagist API, while it claimed to work and did not return errors, did not always abandon the old packages; we'll be auditing those later this week.

So, yes, it's a known issue, and yes, I'll be taking care of it over the next couple of days.
